[package]
name = "m-track"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midly = "0.5"
midir = "0.9"
iced = "0.10"
